/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f8f9ff",
        "secondary-fixed-dim": "#4edea3",
        "on-primary-container": "#7c839b",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-background": "#0b1c30",
        "primary-fixed-dim": "#bec6e0",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary-fixed-variant": "#005236",
        "surface-container-highest": "#d3e4fe",
        "tertiary": "#000000",
        "surface-tint": "#565e74",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#00714d",
        "on-tertiary-fixed": "#191c1e",
        "surface-dim": "#cbdbf5",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-surface": "#0b1c30",
        "error-container": "#ffdad6",
        "secondary-fixed": "#6ffbbe",
        "primary-fixed": "#dae2fd",
        "on-tertiary-container": "#818486",
        "surface-container-high": "#dce9ff",
        "surface-container-low": "#eff4ff",
        "tertiary-fixed": "#e0e3e5",
        "surface": "#f8f9ff",
        "on-primary-fixed": "#131b2e",
        "background": "#f8f9ff",
        "error": "#ba1a1a",
        "surface-variant": "#d3e4fe",
        "outline-variant": "#c6c6cd",
        "on-secondary-fixed": "#002113",
        "surface-container": "#e5eeff",
        "on-primary": "#ffffff",
        "on-surface-variant": "#45464d",
        "inverse-primary": "#bec6e0",
        "secondary-container": "#6cf8bb",
        "on-tertiary-fixed-variant": "#444749",
        "primary-container": "#131b2e",
        "surface-container-lowest": "#ffffff",
        "outline": "#76777d",
        "secondary": "#006c49",
        "brand-emerald": "#10b981",
        "brand-navy": "#0f172a",
        "tertiary-container": "#191c1e",
        "on-primary-fixed-variant": "#3f465c",
        "inverse-surface": "#213145",
        "primary": "#000000"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "4px",
        "space-sm": "8px",
        "space-md": "16px",
        "space-lg": "24px",
        "space-xl": "48px",
        "gutter": "24px",
        "margin": "32px"
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Inter", "system-ui", "sans-serif"]
      }
    },
  },
  plugins: [],
}
